DROP DATABASE IF EXISTS TRUONGHOC1;
CREATE DATABASE TRUONGHOC1;
USE TRUONGHOC1;
SET FOREIGN_KEY_CHECKS = 0;
ALTER DATABASE TRUONGHOC1 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
SET names utf8;

DROP TABLE IF EXISTS TRUONG;
CREATE TABLE TRUONG(
    MATR varchar(9) NOT NULL,
    TENTR varchar(70) NOT NULL,
    DCHITR varchar(200) DEFAULT NULL,
    PRIMARY KEY (MATR)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS HS;
CREATE TABLE HS(
    MAHS varchar(9) NOT NULL,
    HO varchar(12) NOT NULL,
    TEN varchar(12) NOT NULL,
    CCCD varchar(12) DEFAULT NULL,
    NTNS DATE NOT NULL,
    DCHI_HS varchar(200) NOT NULL,
    PRIMARY KEY (MAHS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS HOC;
CREATE TABLE HOC(
    MATR varchar(9) NOT NULL,
    MAHS varchar(9) NOT NULL,
    NAMHOC YEAR NOT NULL,
    DIEMTB float(4),
    XEPLOAI ENUM('Xuất sắc','Giỏi','Khá','Trung bình','Yếu'),
    KQUA ENUM('Hoàn thành','Chưa hoàn thành'),
    PRIMARY KEY (MATR, MAHS, NAMHOC),
    FOREIGN KEY (MATR) REFERENCES TRUONG(MATR),
    FOREIGN KEY (MAHS) REFERENCES HS(MAHS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

SET FOREIGN_KEY_CHECKS = 1;